# Action Cable uses Redis to administer connections, channels, and sending/receiving messages over the WebSocket.
production: &defaults
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  timeout: 1

development:
  <<: *defaults
  url: redis://localhost:6379/2

test:
  <<: *defaults
  url: redis://localhost:6379/3
