# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1593a9aa4736072ebc4477a30094a0a53c968da86536c39987f14584aa33b54cd6773fa5fb0edc793d5bf51611a0304c636d62f969f319909f30b281622c4a0d

test:
  secret_key_base: acf5fbe09dc79e4c4e022e9abdd89f0e7ffca382176a45ba74e63be27d76121dbca846d4eca78f5de3e452259b60fad91585265d780409028f1431b82beef91e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
